- name: Create the dircolors config directory
  file:
      path: ~/.config/dircolors
      state: directory

- name: Deploy dircolors
  file:
      src: "{{ role_path }}/files/solarized-{{ item }}"
      dest: "~/.config/dircolors/solarized-{{ item }}"
      state: link
      force: yes
  loop:
      - dark
      - light

