---
- name: Create the git config directory
  file:
      path: ~/.config/git
      state: directory

- name: Deploy git config
  file:
      src: "{{ role_path }}/files/{{ item }}"
      dest: "~/.config/git/{{ item }}"
      state: link
      force: yes
  loop:
      - config
      - ignore

- name: Create bin directory for additional git commands
  file:
      path: ~/.local/bin
      state: directory

- name: Deploy additional git commands
  file:
      src: "{{ item }}"
      dest: "~/.local/bin/{{ item | basename }}"
      state: link
      force: yes
  with_fileglob:
      - ./bin/*

