#!/bin/bash
# Called by bash (1) on for login shells.
# Source:
#   1. profile if present (XDG_CONFIG_HOME is not defined yet)
#   2. ~/.bashrc if shell is interactive.
[ -f "${HOME}/.config/shell/profile" ] && source "${HOME}/.config/shell/profile"
[[ "$-" == *i* ]] && [ -f "${HOME}/.bashrc" ] && source "${HOME}/.bashrc"

