#!/bin/zsh
# Set up zsh for interactive use (options, prompt, aliases, etc.)

while read -r f; do [ -f "$f" ] && source "$f"; done <<EOL
    ${XDG_CONFIG_HOME}/shell/aliases
    ${XDG_CONFIG_HOME}/shell/solarized
EOL
unset f

stty stop undef # Prevent ctrl-s from freezing the terminal.

# Save a lot of history in the cache directory.
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/history"
HISTSIZE=1000000
SAVEHIST=1000000

