#!/bin/zsh
# Set up zsh for interactive use (options, prompt, aliases, etc.)

stty stop undef # Prevent ctrl-s from freezing the terminal.

[ -f "${XDG_CONFIG_HOME}/shell/aliases.sh" ] && source "${XDG_CONFIG_HOME}/shell/aliases.sh"

