---
- name: bash | remove pre-installed profile
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - ~/.bash_logout
  - ~/.profile


- name: bash | ensure existence of directories used in bashrc
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - ~/.local/share/bash                         # for bash history
  - ~/.local/share/bash-completion/completions  # for custom completions
  - ~/.local/share/less                         # for less history


- name: bash | deploy bash profile
  file:
    src: "{{ role_path }}/files/bashrc"
    dest: "{{ item }}"
    state: link
    force: yes
  loop:
  - ~/.bash_profile     # executed for login shells
  - ~/.bashrc           # executed for interactve shells

