---
- name: mintty | create config directory
  file:
    path: ~/.config/mintty
    state: directory


- name: mintty | deploy config
  file:
    src: "{{ role_path }}/files/minttyrc"
    dest: ~/.config/mintty/config
    state: link
    force: yes

