---
- name: debian | install apt packages
  when: ansible_facts['os_family']|lower == "debian"
  become: yes
  apt:
    state: latest
    update_cache: yes
    name:
    - bash
    - bash-completion
    - curl
    - exa
    - exuberant-ctags
    - ffmpeg
    - git
    - git-crypt
    - git-lfs
    - gpg
    - htop
    - nmap
    - psmisc
    - python3
    - python3-pip
    - shellcheck
    - sqlite
    - stow
    - tmux
    - tree
    - vifm
    - vim
    - wget
    - youtube-dl


- name: macOS | install homebrew packages
  when: ansible_facts['os_family']|lower == "darwin"
  homebrew:
    state: latest
    name:
    - bash
    - bash-completion
    - coreutils
    - ctags
    - curl
    - exa
    - exiftool
    - ffmpeg
    - findutils
    - git
    - git-crypt
    - git-lfs
    - gnu-sed
    - gpg
    - grep
    - gzip
    - htop
    - imagemagick
    - jupyter
    - make
    - nmap
    - pstree
    - python3
    - reattach-to-user-namespace
    - shellcheck
    - sqlite
    - stow
    - tmux
    - tree
    - vifm
    - vim
    - wget
    - youtube-dl

