---
- name: Create the vim cache and config directories
  file:
      path: "{{ item }}"
      state: directory
  loop:
      - "{{ xdg_cache_home }}/vim"
      - "{{ xdg_config_home }}/vim"
      - "{{ xdg_config_home }}/vim/autoload"

- name: Deploy vim plug and vimrc
  file:
      src: "{{ role_path }}/files/{{ item }}"
      dest: "{{ xdg_config_home }}/vim/{{ item }}"
      state: link
      force: yes
  loop:
      - autoload/plug.vim
      - vimrc

- name: Install configured vim plugins
  shell: vim -u "{{ xdg_config_home }}/vim/vimrc" +PlugInstall +qall

